<a href="https://colab.research.google.com/github/Prathamesh-chougale-17/ML-IE/blob/main/IE_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Important Dataset for Preprocessing

In [220]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the Dataset

In [221]:
dataset = pd.read_csv("/content/country_inflation_data.csv")

In [222]:
print(dataset)

      Open  High   Low  Close  Inflation      country ISO3        date
0     0.53  0.54  0.53   0.53        NaN  Afghanistan  AFG  2007-01-01
1     0.53  0.54  0.53   0.53        NaN  Afghanistan  AFG  2007-02-01
2     0.54  0.54  0.53   0.53        NaN  Afghanistan  AFG  2007-03-01
3     0.53  0.55  0.53   0.55        NaN  Afghanistan  AFG  2007-04-01
4     0.56  0.57  0.56   0.57        NaN  Afghanistan  AFG  2007-05-01
...    ...   ...   ...    ...        ...          ...  ...         ...
4793  2.74  2.78  2.70   2.75      -0.28  Yemen, Rep.  YEM  2023-06-01
4794  2.79  2.83  2.75   2.81      -1.85  Yemen, Rep.  YEM  2023-07-01
4795  2.85  2.89  2.81   2.83      -3.17  Yemen, Rep.  YEM  2023-08-01
4796  2.86  2.97  2.82   2.97       1.68  Yemen, Rep.  YEM  2023-09-01
4797  3.06  3.11  2.98   2.98       3.76  Yemen, Rep.  YEM  2023-10-01

[4798 rows x 8 columns]


In [223]:
dataset.shape

(4798, 8)

# Calculating the null Value

In [224]:
dataset.isna().sum()

Open          64
High          64
Low           64
Close         64
Inflation    364
country        0
ISO3           0
date           0
dtype: int64

In [225]:
X = dataset.iloc[:,[0,1,2,3,5,6,7]].values

In [226]:
X

array([[0.53, 0.54, 0.53, ..., 'Afghanistan', 'AFG', '2007-01-01'],
       [0.53, 0.54, 0.53, ..., 'Afghanistan', 'AFG', '2007-02-01'],
       [0.54, 0.54, 0.53, ..., 'Afghanistan', 'AFG', '2007-03-01'],
       ...,
       [2.85, 2.89, 2.81, ..., 'Yemen, Rep.', 'YEM', '2023-08-01'],
       [2.86, 2.97, 2.82, ..., 'Yemen, Rep.', 'YEM', '2023-09-01'],
       [3.06, 3.11, 2.98, ..., 'Yemen, Rep.', 'YEM', '2023-10-01']],
      dtype=object)

In [227]:
y = dataset.iloc[:,4].values

In [228]:
y

array([  nan,   nan,   nan, ..., -3.17,  1.68,  3.76])

## Removing the Null Values

In [229]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy='mean')
X[:,:4]=imputer.fit_transform(X[:,:4])

In [230]:
from sklearn.impute import SimpleImputer
imputery = SimpleImputer(missing_values = np.nan,strategy='mean')
y=imputery.fit_transform(y.reshape(-1, 1))

In [231]:
print(y)

[[14.69234551]
 [14.69234551]
 [14.69234551]
 ...
 [-3.17      ]
 [ 1.68      ]
 [ 3.76      ]]


In [232]:
featurey = pd.DataFrame(y,columns=["Inflation"])

In [233]:
featurey.isna().sum()

Inflation    0
dtype: int64

In [234]:
featurex = pd.DataFrame(X,columns=["Open" , "High" ,  "Low",  "Close"  , "country" ,"ISO3","date"])

In [235]:
featurex.isna().sum()

Open       0
High       0
Low        0
Close      0
country    0
ISO3       0
date       0
dtype: int64

# Normalisation

In [236]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X[:,:4] = scaler.fit_transform(X[:,:4])

In [237]:
feature = pd.DataFrame(X,columns=["Open" , "High" ,  "Low",  "Close"  , "country" ,"ISO3","date"])

In [238]:
print(feature)

          Open      High       Low     Close      country ISO3        date
0     0.005076  0.004978  0.005508  0.005508  Afghanistan  AFG  2007-01-01
1     0.005076  0.004978  0.005508  0.005508  Afghanistan  AFG  2007-02-01
2     0.005173  0.004978  0.005508  0.005508  Afghanistan  AFG  2007-03-01
3     0.005076  0.005072  0.005508   0.00572  Afghanistan  AFG  2007-04-01
4     0.005368   0.00526  0.005826  0.005932  Afghanistan  AFG  2007-05-01
...        ...       ...       ...       ...          ...  ...         ...
4793  0.026647  0.026017  0.028493  0.029022  Yemen, Rep.  YEM  2023-06-01
4794  0.027135  0.026486  0.029022  0.029658  Yemen, Rep.  YEM  2023-07-01
4795  0.027721   0.02705  0.029658   0.02987  Yemen, Rep.  YEM  2023-08-01
4796  0.027818  0.027801  0.029764  0.031353  Yemen, Rep.  YEM  2023-09-01
4797  0.029771  0.029116  0.031459  0.031459  Yemen, Rep.  YEM  2023-10-01

[4798 rows x 7 columns]


In [239]:
print(X)

[[0.005075646656905808 0.004977928054851132 0.005507891113229531 ...
  'Afghanistan' 'AFG' '2007-01-01']
 [0.005075646656905808 0.004977928054851132 0.005507891113229531 ...
  'Afghanistan' 'AFG' '2007-02-01']
 [0.0051732552464616895 0.004977928054851132 0.005507891113229531 ...
  'Afghanistan' 'AFG' '2007-03-01']
 ...
 [0.02772083943387018 0.02704987320371936 0.02965787522508209 ...
  'Yemen, Rep.' 'YEM' '2023-08-01']
 [0.02781844802342606 0.027801258570489342 0.029763796208028808 ...
  'Yemen, Rep.' 'YEM' '2023-09-01']
 [0.02977061981454368 0.02911618296233681 0.031458531935176365 ...
  'Yemen, Rep.' 'YEM' '2023-10-01']]


In [240]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [241]:
X[:,4]= le.fit_transform(X[:,4])

In [242]:
X[:,5]= le.fit_transform(X[:,5])

In [243]:
print(X)

[[0.005075646656905808 0.004977928054851132 0.005507891113229531 ... 0 0
  '2007-01-01']
 [0.005075646656905808 0.004977928054851132 0.005507891113229531 ... 0 0
  '2007-02-01']
 [0.0051732552464616895 0.004977928054851132 0.005507891113229531 ... 0 0
  '2007-03-01']
 ...
 [0.02772083943387018 0.02704987320371936 0.02965787522508209 ... 24 24
  '2023-08-01']
 [0.02781844802342606 0.027801258570489342 0.029763796208028808 ... 24 24
  '2023-09-01']
 [0.02977061981454368 0.02911618296233681 0.031458531935176365 ... 24 24
  '2023-10-01']]


In [244]:
X[:,:4]

array([[0.005075646656905808, 0.004977928054851132, 0.005507891113229531,
        0.005507891113229531],
       [0.005075646656905808, 0.004977928054851132, 0.005507891113229531,
        0.005507891113229531],
       [0.0051732552464616895, 0.004977928054851132,
        0.005507891113229531, 0.005507891113229531],
       ...,
       [0.02772083943387018, 0.02704987320371936, 0.02965787522508209,
        0.029869717190975534],
       [0.02781844802342606, 0.027801258570489342, 0.029763796208028808,
        0.031352610952229645],
       [0.02977061981454368, 0.02911618296233681, 0.031458531935176365,
        0.031458531935176365]], dtype=object)

# Feature Selection

## SelectKBest

In [245]:
from sklearn.feature_selection import SelectKBest, chi2

In [246]:
X1 = SelectKBest(chi2, k=3).fit_transform(X[:,:4], y.astype('int'))

In [247]:
X1

array([[0.004977928054851132, 0.005507891113229531, 0.005507891113229531],
       [0.004977928054851132, 0.005507891113229531, 0.005507891113229531],
       [0.004977928054851132, 0.005507891113229531, 0.005507891113229531],
       ...,
       [0.02704987320371936, 0.02965787522508209, 0.029869717190975534],
       [0.027801258570489342, 0.029763796208028808, 0.031352610952229645],
       [0.02911618296233681, 0.031458531935176365, 0.031458531935176365]],
      dtype=object)

## PCA

In [248]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(X[:,:4])

PCA(n_components=2)

In [249]:
print(pca.explained_variance_ratio_)

[9.98908723e-01 8.68486371e-04]


In [250]:
print(pca.singular_values_)

[6.44482416 0.19003328]


## Select Percentile

In [251]:
from sklearn.feature_selection import SelectPercentile, chi2
X_new = SelectPercentile(chi2, percentile=10).fit_transform(X[:,:4], y.astype('int'))

In [252]:
X_new

array([[0.005507891113229531],
       [0.005507891113229531],
       [0.005507891113229531],
       ...,
       [0.029869717190975534],
       [0.031352610952229645],
       [0.031458531935176365]], dtype=object)

## Variance Threshold

In [253]:
from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold()
selector.fit_transform(X[:,:4])

array([[0.005075646656905808, 0.004977928054851132, 0.005507891113229531,
        0.005507891113229531],
       [0.005075646656905808, 0.004977928054851132, 0.005507891113229531,
        0.005507891113229531],
       [0.0051732552464616895, 0.004977928054851132,
        0.005507891113229531, 0.005507891113229531],
       ...,
       [0.02772083943387018, 0.02704987320371936, 0.02965787522508209,
        0.029869717190975534],
       [0.02781844802342606, 0.027801258570489342, 0.029763796208028808,
        0.031352610952229645],
       [0.02977061981454368, 0.02911618296233681, 0.031458531935176365,
        0.031458531935176365]], dtype=object)