<a href="https://colab.research.google.com/github/Prathamesh-chougale-17/ML-IE/blob/main/IE_ML_121B1B040.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Important Dataset for Preprocessing

In [108]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the Dataset

In [109]:
dataset = pd.read_csv("/content/Global Economy Indicators.csv")

In [110]:
print(dataset)

        CountryID        Country    Year    AMA exchange rate   \
0                4   Afghanistan     1970             0.044998   
1                4   Afghanistan     1971             0.044998   
2                4   Afghanistan     1972             0.044998   
3                4   Afghanistan     1973             0.044998   
4                4   Afghanistan     1974             0.044998   
...            ...            ...     ...                  ...   
10507          894        Zambia     2017             9.519501   
10508          894        Zambia     2018            10.458143   
10509          894        Zambia     2019            12.889418   
10510          894        Zambia     2020            18.344093   
10511          894        Zambia     2021            20.018487   

        IMF based exchange rate    Population   Currency    Per capita GNI   \
0                       0.044998      10752971   Afghani                164   
1                       0.044998      11015857   

In [111]:
dataset.dtypes

 CountryID                                                                                      int64
 Country                                                                                       object
 Year                                                                                           int64
 AMA exchange rate                                                                            float64
 IMF based exchange rate                                                                      float64
 Population                                                                                     int64
 Currency                                                                                      object
 Per capita GNI                                                                                 int64
 Agriculture, hunting, forestry, fishing (ISIC A-B)                                           float64
 Changes in inventories                                                           

In [112]:
dataset.shape

(10512, 26)

# Calculating the null Value

In [113]:
dataset.isna().sum()

 CountryID                                                                                       0
 Country                                                                                         0
 Year                                                                                            0
 AMA exchange rate                                                                               0
 IMF based exchange rate                                                                         0
 Population                                                                                      0
 Currency                                                                                        0
 Per capita GNI                                                                                  0
 Agriculture, hunting, forestry, fishing (ISIC A-B)                                            121
 Changes in inventories                                                                       1841
 Construct

In [114]:
X = dataset.iloc[:,:-1]

In [115]:
X

CountryID        Country    Year    AMA exchange rate   \
0                4   Afghanistan     1970             0.044998   
1                4   Afghanistan     1971             0.044998   
2                4   Afghanistan     1972             0.044998   
3                4   Afghanistan     1973             0.044998   
4                4   Afghanistan     1974             0.044998   
...            ...            ...     ...                  ...   
10507          894        Zambia     2017             9.519501   
10508          894        Zambia     2018            10.458143   
10509          894        Zambia     2019            12.889418   
10510          894        Zambia     2020            18.344093   
10511          894        Zambia     2021            20.018487   

        IMF based exchange rate    Population   Currency    Per capita GNI   \
0                       0.044998      10752971   Afghani                164   
1                       0.044998      11015857   Afghani                168   
2                       0.044998      11286753   Afghani                149   
3                       0.044998      11575305   Afghani                150   
4                       0.044998      11869879   Afghani                177   
...                          ...           ...        ...               ...   
10507                   9.519501      17298054    Kwacha               1448   
10508                  10.458143      17835893    Kwacha               1451   
10509                  12.889418      18380477    Kwacha               1246   
10510                  18.344093      18927715    Kwacha                928   
10511                  20.018487      19473125    Kwacha               1062   

        Agriculture, hunting, forestry, fishing (ISIC A-B)   \
0                                           8.699174e+08      
1                                           9.108281e+08      
2                                           8.279453e+08      
3                                           8.554869e+08      
4                                           1.035913e+09      
...                                                  ...      
10507                                       1.041005e+09      
10508                                       8.791160e+08      
10509                                       6.668385e+08      
10510                                       5.391694e+08      
10511                                       6.285287e+08      

        Changes in inventories   ...  \
0                           NaN  ...   
1                           NaN  ...   
2                           NaN  ...   
3                           NaN  ...   
4                           NaN  ...   
...                         ...  ...   
10507               567729313.0  ...   
10508               929063411.0  ...   
10509               817104395.0  ...   
10510               439295787.0  ...   
10511               293485060.0  ...   

        Gross fixed capital formation (including Acquisitions less disposals of valuables)   \
0                                           9.461182e+07                                      
1                                           9.901235e+07                                      
2                                           1.034568e+08                                      
3                                           1.217284e+08                                      
4                                           1.750619e+08                                      
...                                                  ...                                      
10507                                       1.003902e+10                                      
10508                                       9.238172e+09                                      
10509                                       8.334744e+09                                      
10510                                       5.409199e+09                      

In [116]:
X.dtypes

 CountryID                                                                                      int64
 Country                                                                                       object
 Year                                                                                           int64
 AMA exchange rate                                                                            float64
 IMF based exchange rate                                                                      float64
 Population                                                                                     int64
 Currency                                                                                      object
 Per capita GNI                                                                                 int64
 Agriculture, hunting, forestry, fishing (ISIC A-B)                                           float64
 Changes in inventories                                                           

In [117]:
y = dataset.iloc[:,-1].values

In [118]:
y.shape

(10512,)

In [119]:
y.dtype

dtype('float64')

In [120]:
# X[:,[8,9,11,13,14,15,16,17,18,22,23]]

In [121]:
# columns_X = dataset.columns[:-1]
# print(columns_X)

In [122]:
# columns_y = dataset.columns[-1]
# print(columns_y)

## Removing the Null Values

In [123]:
X.dtypes

 CountryID                                                                                      int64
 Country                                                                                       object
 Year                                                                                           int64
 AMA exchange rate                                                                            float64
 IMF based exchange rate                                                                      float64
 Population                                                                                     int64
 Currency                                                                                      object
 Per capita GNI                                                                                 int64
 Agriculture, hunting, forestry, fishing (ISIC A-B)                                           float64
 Changes in inventories                                                           

In [124]:
int_columns = X.select_dtypes(include=['float64', 'int64']).columns

In [125]:
int_columns

Index([' CountryID ', ' Year ', ' AMA exchange rate ',
       ' IMF based exchange rate ', ' Population ', ' Per capita GNI ',
       ' Agriculture, hunting, forestry, fishing (ISIC A-B) ',
       ' Changes in inventories ', ' Construction (ISIC F) ',
       ' Exports of goods and services ', ' Final consumption expenditure ',
       ' General government final consumption expenditure ',
       ' Gross capital formation ',
       ' Gross fixed capital formation (including Acquisitions less disposals of valuables) ',
       ' Household consumption expenditure (including Non-profit institutions serving households) ',
       ' Imports of goods and services ', ' Manufacturing (ISIC D) ',
       ' Mining, Manufacturing, Utilities (ISIC C-E) ',
       ' Other Activities (ISIC J-P) ', ' Total Value Added ',
       ' Transport, storage and communication (ISIC I) ',
       ' Wholesale, retail trade, restaurants and hotels (ISIC G-H) ',
       ' Gross National Income(GNI) in USD '],
      dtype='

In [126]:
columns_with_nulls = X.columns[X.isnull().any()]

In [127]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy='mean')
# X[:,[8,9,11,13,14,15,16,17,18,22,23]]=imputer.fit_transform(X[:,[8,9,11,13,14,15,16,17,18,22,23]])
X[columns_with_nulls] = pd.DataFrame(imputer.fit_transform(X[columns_with_nulls]), columns=columns_with_nulls)

In [128]:
X.isnull().sum()

 CountryID                                                                                    0
 Country                                                                                      0
 Year                                                                                         0
 AMA exchange rate                                                                            0
 IMF based exchange rate                                                                      0
 Population                                                                                   0
 Currency                                                                                     0
 Per capita GNI                                                                               0
 Agriculture, hunting, forestry, fishing (ISIC A-B)                                           0
 Changes in inventories                                                                       0
 Construction (ISIC F)                  

In [129]:
print(y)

[1.73143559e+09 1.81283752e+09 1.64790018e+09 ... 2.33103622e+10
 1.81106386e+10 2.13133667e+10]


# Normalisation

In [130]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [131]:
int_columns = X.select_dtypes(include=['float64', 'int64']).columns

In [132]:
print(int_columns)

Index([' CountryID ', ' Year ', ' AMA exchange rate ',
       ' IMF based exchange rate ', ' Population ', ' Per capita GNI ',
       ' Agriculture, hunting, forestry, fishing (ISIC A-B) ',
       ' Changes in inventories ', ' Construction (ISIC F) ',
       ' Exports of goods and services ', ' Final consumption expenditure ',
       ' General government final consumption expenditure ',
       ' Gross capital formation ',
       ' Gross fixed capital formation (including Acquisitions less disposals of valuables) ',
       ' Household consumption expenditure (including Non-profit institutions serving households) ',
       ' Imports of goods and services ', ' Manufacturing (ISIC D) ',
       ' Mining, Manufacturing, Utilities (ISIC C-E) ',
       ' Other Activities (ISIC J-P) ', ' Total Value Added ',
       ' Transport, storage and communication (ISIC I) ',
       ' Wholesale, retail trade, restaurants and hotels (ISIC G-H) ',
       ' Gross National Income(GNI) in USD '],
      dtype='

In [133]:
print(X)

        CountryID        Country    Year    AMA exchange rate   \
0                4   Afghanistan     1970             0.044998   
1                4   Afghanistan     1971             0.044998   
2                4   Afghanistan     1972             0.044998   
3                4   Afghanistan     1973             0.044998   
4                4   Afghanistan     1974             0.044998   
...            ...            ...     ...                  ...   
10507          894        Zambia     2017             9.519501   
10508          894        Zambia     2018            10.458143   
10509          894        Zambia     2019            12.889418   
10510          894        Zambia     2020            18.344093   
10511          894        Zambia     2021            20.018487   

        IMF based exchange rate    Population   Currency    Per capita GNI   \
0                       0.044998      10752971   Afghani                164   
1                       0.044998      11015857   

In [134]:
X[int_columns] = scaler.fit_transform(X[int_columns])

In [135]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [136]:
object_columns = X.select_dtypes(include=['object']).columns

In [137]:
# X[object_columns]= le.fit_transform(X[object_columns])
for column in object_columns:
  X[column] = le.fit_transform(X[column])

In [138]:
print(X)

        CountryID    Country      Year    AMA exchange rate   \
0              0.0          0  0.000000         4.030794e-07   
1              0.0          0  0.019608         4.030794e-07   
2              0.0          0  0.039216         4.030794e-07   
3              0.0          0  0.058824         4.030794e-07   
4              0.0          0  0.078431         4.030794e-07   
...            ...        ...       ...                  ...   
10507          1.0        217  0.921569         8.527220e-05   
10508          1.0        217  0.941176         9.368021e-05   
10509          1.0        217  0.960784         1.154587e-04   
10510          1.0        217  0.980392         1.643197e-04   
10511          1.0        217  1.000000         1.793183e-04   

        IMF based exchange rate    Population    Currency    Per capita GNI   \
0                       0.000001      0.007538           0          0.000555   
1                       0.000001      0.007723           0          0.0

# Feature Selection

## SelectKBest

In [139]:
from sklearn.feature_selection import SelectKBest, chi2

In [140]:
X1 = SelectKBest(chi2, k=7).fit_transform(X[int_columns], y)

In [141]:
X1

array([[8.60713740e-05, 3.33214539e-05, 9.82200103e-06, ...,
        3.63036196e-05, 6.42491184e-05, 7.47018203e-05],
       [9.29791453e-05, 3.60043937e-05, 1.02876022e-05, ...,
        3.78872227e-05, 6.72696030e-05, 7.82439559e-05],
       [8.31666136e-05, 3.21932618e-05, 9.34408076e-06, ...,
        3.46760435e-05, 6.11497421e-05, 7.12026833e-05],
       ...,
       [7.23741872e-04, 1.23034310e-03, 4.05427757e-04, ...,
        1.02173432e-03, 1.40882034e-03, 9.70616528e-04],
       [4.99046469e-04, 7.95185970e-04, 3.26851691e-04, ...,
        9.09714205e-04, 9.18719476e-04, 7.44015743e-04],
       [5.92880822e-04, 9.01732377e-04, 3.29414571e-04, ...,
        8.30126484e-04, 1.10259181e-03, 8.76104142e-04]])

## PCA

In [142]:
from sklearn.decomposition import PCA
pca = PCA(n_components=4)
pca.fit(X[int_columns])

PCA(n_components=4)

In [143]:
print(pca.explained_variance_ratio_)

[0.42203246 0.38767624 0.11996401 0.02930496]


In [144]:
print(pca.singular_values_)

[30.19782646 28.94258712 16.10008748  7.95743879]


## Select Percentile

In [145]:
from sklearn.feature_selection import SelectPercentile, chi2
X_new = SelectPercentile(chi2, percentile=10).fit_transform(X[int_columns], y)

In [146]:
X_new

array([[3.33214539e-05, 9.82200103e-06, 7.42078678e-05],
       [3.60043937e-05, 1.02876022e-05, 7.77015516e-05],
       [3.21932618e-05, 9.34408076e-06, 7.06226167e-05],
       ...,
       [1.23034310e-03, 4.05427757e-04, 9.24347510e-04],
       [7.95185970e-04, 3.26851691e-04, 7.37244400e-04],
       [9.01732377e-04, 3.29414571e-04, 8.88846881e-04]])

## Variance Threshold

In [147]:
from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold()
selector.fit_transform(X[int_columns])

array([[0.00000000e+00, 0.00000000e+00, 4.03079417e-07, ...,
        3.63036196e-05, 6.42491184e-05, 7.47018203e-05],
       [0.00000000e+00, 1.96078431e-02, 4.03079417e-07, ...,
        3.78872227e-05, 6.72696030e-05, 7.82439559e-05],
       [0.00000000e+00, 3.92156863e-02, 4.03079417e-07, ...,
        3.46760435e-05, 6.11497421e-05, 7.12026833e-05],
       ...,
       [1.00000000e+00, 9.60784314e-01, 1.15458681e-04, ...,
        1.02173432e-03, 1.40882034e-03, 9.70616528e-04],
       [1.00000000e+00, 9.80392157e-01, 1.64319659e-04, ...,
        9.09714205e-04, 9.18719476e-04, 7.44015743e-04],
       [1.00000000e+00, 1.00000000e+00, 1.79318266e-04, ...,
        8.30126484e-04, 1.10259181e-03, 8.76104142e-04]])