<a href="https://colab.research.google.com/github/Prathamesh-chougale-17/ML-IE/blob/main/shyam/IE_ML_121B1B027.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libraries for Preprocessing

In [76]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the Dataset

In [77]:
dataset = pd.read_csv("/content/accidents_2017.csv")

In [78]:
print(dataset.head)

<bound method NDFrame.head of                     Id District Name           Neighborhood Name  \
0      2017S008429           Unknown                     Unknown   
1      2017S007316           Unknown                     Unknown   
2      2017S010210           Unknown                     Unknown   
3      2017S006364           Unknown                     Unknown   
4      2017S004615        Sant Martí  el Camp de l'Arpa del Clot   
...                ...           ...                         ...   
10334  2017S003667       Sant Andreu               el Bon Pastor   
10335  2017S001896       Sant Andreu               el Bon Pastor   
10336  2017S010718       Sant Andreu               el Bon Pastor   
10337  2017S006145       Sant Andreu               el Bon Pastor   
10338  2017S000178       Sant Andreu               el Bon Pastor   

                                                  Street    Weekday  \
0      Número 27                                     ...     Friday   
1      Núme

In [79]:
dataset.shape

(10339, 15)

# Calculating the null Value

In [80]:
dataset=dataset.drop(dataset.columns[0], axis=1)

In [81]:
dataset=dataset.drop(dataset.columns[13], axis=1)

In [82]:
dataset=dataset.drop(dataset.columns[12], axis=1)

In [83]:
X = dataset.iloc[:,:-1]

In [84]:
X

District Name           Neighborhood Name  \
0           Unknown                     Unknown   
1           Unknown                     Unknown   
2           Unknown                     Unknown   
3           Unknown                     Unknown   
4        Sant Martí  el Camp de l'Arpa del Clot   
...             ...                         ...   
10334   Sant Andreu               el Bon Pastor   
10335   Sant Andreu               el Bon Pastor   
10336   Sant Andreu               el Bon Pastor   
10337   Sant Andreu               el Bon Pastor   
10338   Sant Andreu               el Bon Pastor   

                                                  Street    Weekday  \
0      Número 27                                     ...     Friday   
1      Número 3 Zona Franca / Número 50 Zona Franca  ...     Friday   
2      Litoral (Besòs)                               ...     Friday   
3      Número 3 Zona Franca                          ...     Friday   
4      Las Navas de Tolosa                           ...   Thursday   
...                                                  ...        ...   
10334  Litoral (Llobregat)                           ...    Tuesday   
10335  PL MONTERREY                                  ...  Wednesday   
10336  Litoral (Llobregat)                           ...   Thursday   
10337  Litoral (Besòs)                               ...     Friday   
10338  CIUTAT D'ASUNCIÓN                             ...     Sunday   

           Month  Day  Hour Part of the day  Mild injuries  Serious injuries  \
0        October   13     8         Morning              2                 0   
1      September    1    13         Morning              2                 0   
2       December    8    21       Afternoon              5                 0   
3           July   21     2           Night              1                 0   
4            May   25    14       Afternoon              1                 0   
...          ...  ...   ...             ...            ...               ...   
10334      April   25     8         Morning              1                 0   
10335      March    8    12         Morning              1                 0   
10336   December   28     8         Morning              1                 0   
10337       July   14    14       Afternoon              1                 0   
10338    January    8    20       Afternoon              0                 0   

       Victims  
0            2  
1            2  
2            5  
3            1  
4            1  
...        ...  
10334        1  
10335        1  
10336        1  
10337        1  
10338        0  

[10339 rows x 11 columns]

In [85]:
y = dataset.iloc[:,-1].values

In [86]:
y

array([2, 2, 2, ..., 2, 2, 1])

In [87]:
y.shape

(10339,)

In [88]:
y.dtype

dtype('int64')

## Removing the Null Values

In [89]:
X.dtypes

District Name        object
Neighborhood Name    object
Street               object
Weekday              object
Month                object
Day                   int64
Hour                  int64
Part of the day      object
Mild injuries         int64
Serious injuries      int64
Victims               int64
dtype: object

In [90]:
columns_with_nulls = X.columns[X.isnull().any()]

In [91]:
dataset.isna().sum()

District Name        0
Neighborhood Name    0
Street               0
Weekday              0
Month                0
Day                  0
Hour                 0
Part of the day      0
Mild injuries        0
Serious injuries     0
Victims              0
Vehicles involved    0
dtype: int64

# Normalisation

In [92]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [93]:
int_columns = X.select_dtypes(include=['float64', 'int64']).columns

In [94]:
print(int_columns)

Index(['Day', 'Hour', 'Mild injuries', 'Serious injuries', 'Victims'], dtype='object')


In [95]:
X[int_columns] = scaler.fit_transform(X[int_columns])

In [96]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [97]:
X.dtypes

District Name         object
Neighborhood Name     object
Street                object
Weekday               object
Month                 object
Day                  float64
Hour                 float64
Part of the day       object
Mild injuries        float64
Serious injuries     float64
Victims              float64
dtype: object

In [98]:
object_columns = X.select_dtypes(include=['object']).columns

In [99]:
X

District Name           Neighborhood Name  \
0           Unknown                     Unknown   
1           Unknown                     Unknown   
2           Unknown                     Unknown   
3           Unknown                     Unknown   
4        Sant Martí  el Camp de l'Arpa del Clot   
...             ...                         ...   
10334   Sant Andreu               el Bon Pastor   
10335   Sant Andreu               el Bon Pastor   
10336   Sant Andreu               el Bon Pastor   
10337   Sant Andreu               el Bon Pastor   
10338   Sant Andreu               el Bon Pastor   

                                                  Street    Weekday  \
0      Número 27                                     ...     Friday   
1      Número 3 Zona Franca / Número 50 Zona Franca  ...     Friday   
2      Litoral (Besòs)                               ...     Friday   
3      Número 3 Zona Franca                          ...     Friday   
4      Las Navas de Tolosa                           ...   Thursday   
...                                                  ...        ...   
10334  Litoral (Llobregat)                           ...    Tuesday   
10335  PL MONTERREY                                  ...  Wednesday   
10336  Litoral (Llobregat)                           ...   Thursday   
10337  Litoral (Besòs)                               ...     Friday   
10338  CIUTAT D'ASUNCIÓN                             ...     Sunday   

           Month       Day      Hour Part of the day  Mild injuries  \
0        October  0.400000  0.347826         Morning            0.2   
1      September  0.000000  0.565217         Morning            0.2   
2       December  0.233333  0.913043       Afternoon            0.5   
3           July  0.666667  0.086957           Night            0.1   
4            May  0.800000  0.608696       Afternoon            0.1   
...          ...       ...       ...             ...            ...   
10334      April  0.800000  0.347826         Morning            0.1   
10335      March  0.233333  0.521739         Morning            0.1   
10336   December  0.900000  0.347826         Morning            0.1   
10337       July  0.433333  0.608696       Afternoon            0.1   
10338    January  0.233333  0.869565       Afternoon            0.0   

       Serious injuries  Victims  
0                   0.0      0.2  
1                   0.0      0.2  
2                   0.0      0.5  
3                   0.0      0.1  
4                   0.0      0.1  
...                 ...      ...  
10334               0.0      0.1  
10335               0.0      0.1  
10336               0.0      0.1  
10337               0.0      0.1  
10338               0.0      0.0  

[10339 rows x 11 columns]

In [100]:
for column in object_columns:
  X[column] = le.fit_transform(X[column])

In [101]:
X.dtypes

District Name          int64
Neighborhood Name      int64
Street                 int64
Weekday                int64
Month                  int64
Day                  float64
Hour                 float64
Part of the day        int64
Mild injuries        float64
Serious injuries     float64
Victims              float64
dtype: object

In [102]:
int_columns = X.select_dtypes(include=['float64', 'int64']).columns

# Feature Selection

## SelectKBest

In [103]:
from sklearn.feature_selection import SelectKBest, chi2

In [104]:
X1 = SelectKBest(chi2, k=2).fit_transform(X[int_columns], y)

In [105]:
X1

array([[  24., 2661.],
       [  24., 2666.],
       [  24., 2157.],
       ...,
       [  33., 2158.],
       [  33., 2157.],
       [  33.,  727.]])

## PCA

In [106]:
from sklearn.decomposition import PCA
pca = PCA(n_components=4)
pca.fit(X[int_columns])

PCA(n_components=4)

In [107]:
print(pca.explained_variance_ratio_)

[9.99720220e-01 2.62633005e-04 7.69829932e-06 6.01192336e-06]


In [108]:
print(pca.singular_values_)

[123717.54823361   2005.24165667    343.31237888    303.38826926]


## Select Percentile

In [109]:
from sklearn.feature_selection import SelectPercentile, chi2
X_new = SelectPercentile(chi2, percentile=10).fit_transform(X[int_columns], y)

In [110]:
X_new

array([[2661.],
       [2666.],
       [2157.],
       ...,
       [2158.],
       [2157.],
       [ 727.]])

## Variance Threshold

In [111]:
from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold()
selector.fit_transform(X[int_columns])

array([[1.000e+01, 2.400e+01, 2.661e+03, ..., 2.000e-01, 0.000e+00,
        2.000e-01],
       [1.000e+01, 2.400e+01, 2.666e+03, ..., 2.000e-01, 0.000e+00,
        2.000e-01],
       [1.000e+01, 2.400e+01, 2.157e+03, ..., 5.000e-01, 0.000e+00,
        5.000e-01],
       ...,
       [6.000e+00, 3.300e+01, 2.158e+03, ..., 1.000e-01, 0.000e+00,
        1.000e-01],
       [6.000e+00, 3.300e+01, 2.157e+03, ..., 1.000e-01, 0.000e+00,
        1.000e-01],
       [6.000e+00, 3.300e+01, 7.270e+02, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

In [112]:
X

District Name  Neighborhood Name  Street  Weekday  Month       Day  \
0                 10                 24    2661        0     10  0.400000   
1                 10                 24    2666        0     11  0.000000   
2                 10                 24    2157        0      2  0.233333   
3                 10                 24    2663        0      5  0.666667   
4                  7                 35    2117        4      8  0.800000   
...              ...                ...     ...      ...    ...       ...   
10334              6                 33    2158        5      0  0.800000   
10335              6                 33    2879        6      7  0.233333   
10336              6                 33    2158        4      2  0.900000   
10337              6                 33    2157        0      5  0.433333   
10338              6                 33     727        3      4  0.233333   

           Hour  Part of the day  Mild injuries  Serious injuries  Victims  
0      0.347826                1            0.2               0.0      0.2  
1      0.565217                1            0.2               0.0      0.2  
2      0.913043                0            0.5               0.0      0.5  
3      0.086957                2            0.1               0.0      0.1  
4      0.608696                0            0.1               0.0      0.1  
...         ...              ...            ...               ...      ...  
10334  0.347826                1            0.1               0.0      0.1  
10335  0.521739                1            0.1               0.0      0.1  
10336  0.347826                1            0.1               0.0      0.1  
10337  0.608696                0            0.1               0.0      0.1  
10338  0.869565                0            0.0               0.0      0.0  

[10339 rows x 11 columns]